### PR TITLE
Introduce .build_ignore file

### PR DESCRIPTION
**Pull request by manuraj17**
Relates to https://github.com/newrelic/newrelic-ruby-agent/issues/1150

The requirement was to reduce the number of files that were added to the release build.

Introducing a new simple text file `.build_ignore` which containst the list of files to be rejected. In the gemspec file we update the `reject` method definition to reject files listed in this file. It involes nested loops at the moment so not the best of efficiency, although we are dealing with very less amount of data hence should not take up too much time. We can always look into optimisations. We can treat this as a starting point. 

Changes are only currently added to `newrelic_rpm.gemspec` to get feedback. 

This is one of my first contribution here, so aplogies in advance if I have broken any contribution guidelines uknowingly. Please call it out so that I can correct them.

### CODE REVIEW

**Comment by tannalynn** [comment]
Thanks for contributing! It looks like bundler ran into an issue parsing this change. This is the output:
```
>Run bundle

[!] There was an error parsing `Gemfile`: 
[!] There was an error while loading `newrelic_rpm.gemspec`: undefined local variable or method `rf' for main:Object. Bundler cannot continue.

 #  from /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/newrelic_rpm.gemspec:[4](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5319812254/jobs/9643514662?pr=2089#step:5:5)2
 #  -------------------------------------------
 #    reject_list = File.read("./.build_ignore").split("\n")
 >    file_list = `git ls-files -z`.split("\x0").reject { |f| reject_list.any? |rf| f.start_with?(rf)  }
 #    build_file_path = 'lib/new_relic/build.rb'
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/Gemfile:[6](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5319812254/jobs/9643514662?pr=2089#step:5:7)
 #  -------------------------------------------
 #  source 'https://rubygems.org/'
 >  gemspec name: 'newrelic_rpm'
 #  -------------------------------------------
```
Once this is addressed, I'll take a look again and make sure everything is good!

**Comment by manuraj17** [comment]
@tannalynn My bad! I missed out a bracket, since there were no tests for this I just added the snippet and pushed for feedback. I have made changes and tried building the gem as well.

**Comment by manuraj17** [comment]
@tannalynn I had force pushed the changes to keep the commit history clean of minor changes - I forgot to confirm if that was a habit followed here. You might want to delete and pull this branch again to avoid conflicts. Sorry about that, will restrict to normal push.

**Review by tannalynn — APPROVED** [review]
Thanks for working on this! The tests failing are unrelated to this PR and are already fixed on dev, so I'm going to go ahead and merge this. We appreciate the contribution!

**Pull request merged**
