### PR TITLE
Update for httprb 5.0.0

### PR DESCRIPTION
**Pull request by tannalynn**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
This PR fixes the breaking change httprb 5.0.0 introduces into our test suite, and adds that version back to our multiverse testing. The change made that caused the failures was related to this change https://github.com/httprb/http/pull/546. Our instrumentation was not affected, but our test suite needed to be updated to create response objects correctly in 5.0.0. 

# Related Github Issue
closes https://github.com/newrelic/newrelic-ruby-agent/issues/674

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
Github Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

**Comment by kaylareopelle** [comment]
Yikes -- I just noticed this on httprb's repo: https://github.com/httprb/http/commit/efe274a70e3b866a0a9444fe2eef2c9dd4930830 

I think it might be safe to say that HTTP 5.0 doesn't support jruby if the CI is not running against it.

**Comment by tannalynn** [comment]
> Yikes -- I just noticed this on httprb's repo: [httprb/http@efe274a](https://github.com/httprb/http/commit/efe274a70e3b866a0a9444fe2eef2c9dd4930830)
> 
> I think it might be safe to say that HTTP 5.0 doesn't support jruby if the CI is not running against it.

Oh yikes, yeah... Well at least we know it isn't our instrumentation causing the issue. I don't think they mentioned that in their changelog when I looked, so that's surprising. 

Since that's the case, all we need to do is exclude 5.0.0+ from running on jruby in multiverse.

**Comment by kaylareopelle** [comment]
Nice. We might want to update the docs noting JRuby isn't supported for HTTP.rb 5.0.0+ as well.

**Review by kaylareopelle — APPROVED** [review]
LGTM! Phew!

**Pull request merged**
