### PR TITLE
Refactor NewRelic::Agent::Agent to reduce size

### PR DESCRIPTION
**Pull request by tannalynn**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
This moves related/similar methods into different modules to be included into Agent::Agent. Agent::Agent is only 371 lines long now! 

Also, I renamed the directory the new modules were in and even though i used git mv to do it, the pr is still showing the files that were there before as being deleted and creating new ones, I have no idea why. Isn't that the whole point of using git mv??   🤷 

previous pr that did a partial refactor: https://github.com/newrelic/newrelic-ruby-agent/pull/1192
closes https://github.com/newrelic/newrelic-ruby-agent/issues/999

Submitter Checklist:
- [ ] Include a link to the related GitHub issue, if applicable
- [ ] Include a security review link, if applicable

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
GitHub Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

**Review by fallwith — CHANGES_REQUESTED** [review]
The refactoring looks great and should really help keep things more manageable. I'm already seeing things jump out at me in the smaller classes that I immediately feel more comfortable considering for a change or a removal given the better readability and smaller contexts. Great work!

I have a small request and that's to keep all newly added lines to the project at or under 120 columns in length. Now technically the long lines in the PR are just moved and not "new" per se, but I think we might as well get the line length down while we're refactoring the code already.

**Comment by kaylareopelle** [comment]
I haven't closely looked at this yet, but James's comment made me think of the Rubocop AbcSize linter. It might be nice to run the new classes through that TODO-listed linter too.

**Review by fallwith — APPROVED** [review]

**Review by kaylareopelle — APPROVED** [review]
Thank you, Tanna!

**Comment by fallwith** [comment]
(team agreed to go ahead and merge this one)

**Pull request merged**
