### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nbolser**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
Documentation typo fix. Sorry. My OCD kicked in.

# Related Github Issue
N/A

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
Github Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes.

### CODE REVIEW

**Comment by mwlang** [comment]
@nbolser, thank you for submitting this fix!  Happy to accept even the minor fixes.  If you could sign the CLA, we can then merge your PR and wipe out that typo.

**Review by angelatan2 — APPROVED** [review]
Thanks for updating the typo.

**Comment by angelatan2** [comment]
@nbolser thanks for the updates.  We appreciate the contribution. Please note that we would appreciate it if you can sign the CLA for future code contributions.  It's a process step that we apply across all New Relic Open Source repositories.

**Comment by nbolser** [comment]
@angelatan2 Hi. Sorry about that. I'm just catching up on this account now. Noted for future contributions. Happy to help, even if very minor.

**Pull request merged**
