### PR TITLE
Scrub non-unicode characters from logger

### LINKED ISSUE #842: DecoratingLogger throws JSON::GeneratorError on invalid encodings
## Description
We log user agents in our Rails requests. Some clients send dubious http headers which might not be a valid string, and if we log those to NewRelic::Agent::Logging::DecoratingLogger, it throws a JSON::GeneratorError: 

```
JSON::GeneratorError
Invalid Unicode [6e 7a 65 6e 64] at 113

activesupport (6.1.4.1) lib/active_support/core_ext/object/json.rb in to_json at line 43
newrelic_rpm (8.1.0) lib/new_relic/agent/logging.rb in escape at line 91
newrelic_rpm (8.1.0) lib/new_relic/agent/logging.rb in call at line 68
logger.rb in format_message at line 585
newrelic_rpm (8.1.0) lib/new_relic/agent/instrumentation/logger/prepend.rb in block in format_message at line 10
newrelic_rpm (8.1.0) lib/new_relic/agent/instrumentation/logger/instrumentation.rb in format_message_with_tracing at line 36
newrelic_rpm (8.1.0) lib/new_relic/agent/instrumentation/logger/prepend.rb in format_message at line 10
activesupport (6.1.4.1) lib/active_support/logger_thread_safe_level.rb in add at line 75
activesupport (6.1.4.1) lib/active_support/logger.rb in block (2 levels) in broadcast at line 26
logger.rb in info at line 528
```

One example agent is "Mac OS X / Safari 12 [Desktop]: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5 (Ergänzendes Update)) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15"

## Expected Behavior

The logger should either replace invalid characters with � (as the standard Rails logger does), fail silently, or it might log a line saying something to the effect of "invalid encoding in log message".

## Steps to Reproduce
Please be as specific as possible.

```ruby
Rails.logger.info "Hello \xb3"
```

## Your Environment

Ruby 2.7.4
NewRelic 8.1.0
Rails 6.1.4.1

### PR DESCRIPTION
**Pull request by kaylareopelle**
# Overview
Adds a call to`#scrub` with a replacement character to avoid raising a `JSON::GeneratorError` when non-unicode characters are included in log messages.

`#scrub` was chosen over `#encode` due to better performance when running benchmark tests.

# Related Github Issue
Closes #842 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

**Comment by kaylareopelle** [comment]
The String class's `#encode` and `#scrub` methods are both quite performant, but `#scrub` is the clear winner imo: 

```
# encode_vs_scrub.rb 

Allocations -------------------------------------
              encode       6/0  alloc/ret        2/0  strings/ret
               scrub       2/0  alloc/ret        2/0  strings/ret
Warming up --------------------------------------
              encode    83.578k i/100ms
               scrub   177.312k i/100ms
Calculating -------------------------------------
              encode      1.494M (± 2.3%) i/s -      7.522M
               scrub      7.710M (± 4.8%) i/s -     38.477M
```

**Review by tannalynn — COMMENTED** [review]
Looks great! We do need to add it to the changelog though.

**Comment by kaylareopelle** [comment]
> Looks great! We do need to add it to the changelog though.

Got it! :)

**Review by tannalynn — APPROVED** [review]
Thanks for adding it to the changelog!

**Pull request merged**
