### PR TITLE
[DO NOT MERGE] Hotfix/infinite tracing no data

### PR DESCRIPTION
**Pull request by mwlang**
This is a PR intended to make it easy for customers to use the hotfix for Infinite Tracing that fixes an issue where enabling Infinite Tracing can sometimes lead to no data reported.

#### Do not merge!
This fix is already merged to `dev` and will be removed when 7.0 is released.

### CODE REVIEW

**Comment by mwlang** [comment]
To use this hotfix, add the following to your Gemfile.

This is based off the 6.15.0 release and patches only Infinite Tracing:

```Ruby
gem 'newrelic_rpm', 
  :git => 'https://github.com/newrelic/newrelic-ruby-agent.git',  
  :branch => 'hotfix/infinite_tracing_no_data'
```

**Comment by rokcarl** [comment]
Are you sure it should be `gem 'newrelic_rpm'`? Previously I've gotten instructions to modify the `newrelic-infinite_tracing`, I would expect it to be the same this time as well? I.e. for us this would mean:

```
gem "newrelic_rpm", "~> 6.15"
gem 'newrelic-infinite_tracing',
  :git => 'https://github.com/newrelic/newrelic-ruby-agent.git',  
  :branch => 'hotfix/infinite_tracing_no_data'
```

**Comment by mwlang** [comment]
@rokcarl -- you're right.  The correct way to deploy this fix presently is:

```ruby
gem "newrelic_rpm", "~> 6.15"
gem 'newrelic-infinite_tracing',
  :git => 'https://github.com/newrelic/newrelic-ruby-agent.git',  
  :branch => 'hotfix/infinite_tracing_no_data'
```

**Comment by tannalynn** [comment]
This fix has been released in our 7.0.0 version of the agent. Please upgrade to this version for this fix.

**Pull request closed without merging**
