### PR TITLE
Make references to NewRelic consistent

### PR DESCRIPTION
**Pull request by fchatterji**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
Pull request to make references to newrelic more consistent in the codebase, except in proto files and their dependencies

github issue: https://github.com/newrelic/newrelic-ruby-agent/issues/1656

Submitter Checklist:
- [X] Include a link to the related GitHub issue, if applicable
- [ ] Include a security review link, if applicable

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
GitHub Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

**Comment by fchatterji** [comment]
I fixed the failing tests, some renaming was needed

**Comment by hannahramadan** [comment]
Hi @fchatterji 👋 Thanks for submitting this PR and congrats on your first open source contribution 🥳

Your PR looks great so far! There are a few more changes that we'd love to see if you're open to making those updates. I'm also happy to merge as-is.

Based on the sequel-related file name change of `newrelic_instrumentation` to `new_relic_instrumentation`, we will need to update a few other places that use this. Instances of `newrelic_instrumentation` should be changed to `new_relic_instrumentation` in the following  files:
- `lib/new_relic/agent/instrumentation/sequel.rb`
- `lib/sequel/extensions/newrelic_instrumentation.rb`
- `test/multiverse/suites/sequel/sequel_extension_test.rb`
- `test/multiverse/suites/sequel/sequel_helpers.rb`

**Review by hannahramadan — APPROVED** [review]
Thanks for making the additional updates. This looks great @fchatterji! I'll go ahead and merge your PR.

**Comment by hannahramadan** [comment]
Hey @fchatterji! We needed to make an update to our CI, which is why your `dev` merge failed. I wanted to follow up with [the successful run](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/4128288613) of your PR. Thanks again for your contribution 😄

**Comment by fchatterji** [comment]
@hannahramadan yes that's what i thought, great. By the way, I noticed that you still have some newrelic_instrumentation in lib/new_relic/agent/instrumentation/active_record.rb. If you want I could change those too.

**Comment by hannahramadan** [comment]
Thanks for checking @fchatterji! All those instances of the string `newrelic_instrumentation` are found within the name of a method, either `log_with_newrelic_instrumentation` or `log_without_newrelic_instrumentation`. These are safe to leave as-is.

**Pull request merged**
