### PR TITLE
Update ci to use jruby 9.3.0.0

### PR DESCRIPTION
**Pull request by kaylareopelle**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
JRuby 9.3.0.0 was released today (September 22). This is a test to observe how our CI reacts.

# Related Github Issue
Closes: https://github.com/newrelic/newrelic-ruby-agent/issues/788 

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
Github Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

**Comment by kaylareopelle** [comment]
ruby-build does not yet have a definition for jruby-9.3.0.0. We'll need to wait until that's available to make this change.

**Comment by kaylareopelle** [comment]
I created an issue on the ruby-build repo to find out when they plan to have JRuby 9.3.0.0 support: https://github.com/rbenv/ruby-build/issues/1796

**Comment by kaylareopelle** [comment]
Closing this draft PR as the update is not currently being worked on. JRuby 9.3+ support is included in our backlog.

**Comment by ahorek** [comment]
do you want me to create a new PR? this is really simple to fix

**Comment by kaylareopelle** [comment]
@ahorek  - It would be great if you could create a new PR to resolve this issue! Unfortunately we have other priorities at the moment and have fallen behind on our JRuby support.

**Pull request closed without merging**
