### PR TITLE
Scheduled CI tests run despite rubocop failures

### PR DESCRIPTION
**Pull request by tannalynn**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
This removes the rubocop dependency for the our test jobs in our ci_cron.yml. We will still be notified of the rubocop failure, but we will also still have all of our tests run each night as well. This will make sure we don't miss any new failures unrelated to a new rubocop version.

Submitter Checklist:
- [ ] Include a link to the related GitHub issue, if applicable
- [ ] Include a security review link, if applicable

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
GitHub Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

**Review by fallwith — APPROVED** [review]

**Review by kaylareopelle — APPROVED** [review]
💀 🦄

**Review by kaylareopelle — COMMENTED** [review]
If we're not calling `run-rubocop` anymore, should we delete lines 11-22?

**Comment by tannalynn** [comment]
> If we're not calling `run-rubocop` anymore, should we delete lines 11-22?

The rubocop job will still run like this actually. The difference is that now if it fails the tests will run anyways. So we'll get a slack notification if only the rubocop job fails, but this way we'll know if any test failures happen also.

**Comment by kaylareopelle** [comment]
> > If we're not calling `run-rubocop` anymore, should we delete lines 11-22?
> 
> The rubocop job will still run like this actually. The difference is that now if it fails the tests will run anyways. So we'll get a slack notification if only the rubocop job fails, but this way we'll know if any test failures happen also.

Thanks for clarifying!

**Pull request merged**
