### PR TITLE
Remove NewRelic::Metrics file because there are not references to it

### PR DESCRIPTION
**Pull request by csaura**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
Reviewing the code I was curious about this file and I didn't found any reference. As it seems is not used and was created 11y ago, maybe can be removed

# Related Github Issue
It's a super tiny change for opening an issue, but if you think I should do it, just let me know.

# Testing
The removed file only contains constants and I didn't found tests to do or remove.

### CODE REVIEW

**Comment by tannalynn** [comment]
Thank you for contributing to the ruby agent! We will take a look and review this soon.

**Comment by mwlang** [comment]
@csuara, we are in the process of migrating our continuous integration from Travis CI to github actions.  Once we're done with this effort, we'll circle back to this PR to review and merge.  On the surface, it looks good, so is pending completion of our CI work at this point.

**Comment by tannalynn** [comment]
Now that we have our CI set up, I'm going to close and reopen this PR to retrigger the fresh CI.

**Comment by mwlang** [comment]
All tests pass.  Looks good to me.  Approving for merge.

**Comment by mwlang** [comment]
@csaura Thank you for your PR and patience while we got our continuous integration setup for open source releases.  Your PR is merged to `dev` and will appear in the next release of the agent.

**Comment by csaura** [comment]
Great! I am super happy to help 💪

**Pull request merged**
