### PR TITLE
Adds Amazon Timestream ActiveRecord Adapter

### PR DESCRIPTION
**Pull request by wagner**
# Overview
This pull request adds the [Amazon Timestream ActiveRecord Adapter](https://rubygems.org/gems/activerecord-amazon-timestream-adapter) to the list of known AR adapters. I don't know which are the requirements for relevance here, but if this gem doesn't meet them, let me know.

Submitter Checklist:
- ~[ ] Include a link to the related GitHub issue, if applicable~ N/A
- ~[ ] Include a security review link, if applicable~ N/A

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

**Review by fallwith — APPROVED** [review]

**Comment by fallwith** [comment]
Hi @wagner, thanks very much for this contribution!

Typically a new adapter value gets added for one of two reasons: a) in order to tell the agent how to treat the adapter when it comes to something such as SQL obfuscation (see the `DIALECT_COMPONENTS` and `CLEANUP_REGEX` constants in [lib/new_relic/agent/database/obfuscation_helpers.rb](https://github.com/newrelic/newrelic-ruby-agent/blob/dev/lib/new_relic/agent/database/obfuscation_helpers.rb)), and b) for display purposes.

If this PR helps your use case, then we are quite happy to bring it in. If there is anything else you'd like to see done to better offer support for the Timestream adapter, please let us know.

Also, do you happen to know if that adapter is still actively maintained or if there are other Timestream adapters available? I see that the adapter is pinned to Rails <= 6 and not compatible with Rails 7, so I'm curious about what users will do when they want to use Rails 7+.

**Comment by fallwith** [comment]
This change should be released as part of the next v9.x.x agent release. Thanks again!

**Comment by wagner** [comment]
> Also, do you happen to know if that adapter is still actively maintained or if there are other Timestream adapters available? 

No, that's the only one, as far as I know. 

> I see that the adapter is pinned to Rails <= 6 and not compatible with Rails 7, so I'm curious about what users will do when they want to use Rails 7+.

I'm not the author, but it looks like Rails 7 support was [added](https://github.com/fdeschenes/activerecord-amazon-timestream-adapter/commit/e651a63bbfd8544cdc3a33d6499baac885763488) on the `main` branch, although not officially released.

Thanks for merging!

**Comment by fallwith** [comment]
Hi @wagner, your contribution was included with v9.1.0 of the gem that was just released. Thanks again!

**Pull request merged**
